CREATE SCHEMA IF NOT EXISTS roster_reconciler;

CREATE TABLE IF NOT EXISTS roster_reconciler.roster_runs (
  id uuid PRIMARY KEY,
  app text NOT NULL,
  previous_path text NOT NULL,
  current_path text NOT NULL,
  key_columns text[] NOT NULL,
  key_normalize text NOT NULL,
  value_normalize text NOT NULL,
  summary_only boolean NOT NULL,
  detail_limit integer,
  export_dir text,
  export_unchanged boolean NOT NULL,
  export_updated_rows boolean NOT NULL,
  export_status boolean NOT NULL,
  json_path text,
  started_at timestamptz NOT NULL,
  finished_at timestamptz NOT NULL,
  duration_ms integer NOT NULL,
  total_previous integer NOT NULL,
  total_current integer NOT NULL,
  added integer NOT NULL,
  removed integer NOT NULL,
  updated integer NOT NULL,
  unchanged integer NOT NULL,
  duplicate_previous integer NOT NULL,
  duplicate_current integer NOT NULL,
  invalid_previous integer NOT NULL,
  invalid_current integer NOT NULL,
  net_change integer NOT NULL,
  net_change_pct_previous numeric,
  added_pct_current numeric,
  removed_pct_previous numeric,
  updated_pct_shared numeric,
  unchanged_pct_shared numeric,
  field_change_counts jsonb,
  missing_key_counts_previous jsonb,
  missing_key_counts_current jsonb,
  completeness_previous jsonb,
  completeness_current jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS roster_runs_started_at_idx
  ON roster_reconciler.roster_runs (started_at);
