INSERT INTO roster_reconciler.roster_runs (
  id, app, previous_path, current_path, key_columns, key_normalize, value_normalize,
  summary_only, detail_limit, export_dir, export_unchanged, export_updated_rows, export_status,
  json_path, started_at, finished_at, duration_ms, total_previous, total_current, added, removed,
  updated, unchanged, duplicate_previous, duplicate_current, invalid_previous, invalid_current,
  net_change, net_change_pct_previous, added_pct_current, removed_pct_previous, updated_pct_shared,
  unchanged_pct_shared, field_change_counts, missing_key_counts_previous, missing_key_counts_current,
  completeness_previous, completeness_current
) VALUES (
  '0b7d3f75-9e7c-4d5f-9b8b-3af18d1b1b6e',
  'roster-reconciler',
  'data/roster_prev.csv',
  'data/roster_current.csv',
  ARRAY['email'],
  'none',
  'none',
  false,
  NULL,
  'out/exports',
  true,
  true,
  true,
  'report.json',
  '2026-02-08T17:00:00Z',
  '2026-02-08T17:00:05Z',
  5000,
  120,
  124,
  6,
  2,
  4,
  108,
  1,
  0,
  0,
  0,
  4,
  3.33,
  4.84,
  1.67,
  3.57,
  96.43,
  '{"status":4,"cohort":2}'::jsonb,
  '{}'::jsonb,
  '{}'::jsonb,
  '{"email":{"non_empty":120,"total":120,"pct":100.0},"cohort":{"non_empty":118,"total":120,"pct":98.3333}}'::jsonb,
  '{"email":{"non_empty":124,"total":124,"pct":100.0},"cohort":{"non_empty":123,"total":124,"pct":99.1935}}'::jsonb
);
