INSERT INTO roster_reconciler.roster_reconciler_runs (
  run_id, app_name, started_at, finished_at, previous_path, current_path, key_columns,
  key_normalize, value_normalize, summary_only, detail_limit, total_previous, total_current,
  added, removed, updated, unchanged, duplicate_keys_previous, duplicate_keys_current,
  invalid_rows_previous, invalid_rows_current, net_change, shared_count, added_columns,
  removed_columns, ignored_fields, unknown_ignored_fields, export_dir, export_unchanged,
  export_updated_rows, export_status, json_path
) VALUES (
  '0b7d3f75-9e7c-4d5f-9b8b-3af18d1b1b6e',
  'roster-reconciler',
  '2026-02-08T17:00:00Z',
  '2026-02-08T17:00:05Z',
  'data/roster_prev.csv',
  'data/roster_current.csv',
  'email',
  'none',
  'none',
  false,
  NULL,
  120,
  124,
  6,
  2,
  4,
  108,
  1,
  0,
  0,
  0,
  4,
  112,
  NULL,
  NULL,
  'last_login',
  NULL,
  'out/exports',
  true,
  true,
  true,
  'report.json'
);
